/*
 * (C) Copyright IBM Corp. 2022.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package com.ibm.cloud.mdm.v1.model;

import com.google.gson.annotations.SerializedName;
import com.ibm.cloud.sdk.core.service.model.GenericModel;

/**
 * The size statistics of entities generated by the match process.
 */
public class MatchEntitySizeStats extends GenericModel {

  @SerializedName("entity_id")
  protected String entityId;
  @SerializedName("entity_size")
  protected Double entitySize;

  /**
   * Gets the entityId.
   *
   * The identifier of the entity.
   *
   * @return the entityId
   */
  public String getEntityId() {
    return entityId;
  }

  /**
   * Gets the entitySize.
   *
   * The size of this entity.
   *
   * @return the entitySize
   */
  public Double getEntitySize() {
    return entitySize;
  }
}

