/*
 * (C) Copyright IBM Corp. 2022.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package com.ibm.cloud.mdm.v1.model;

import com.google.gson.annotations.SerializedName;
import com.ibm.cloud.sdk.core.service.model.GenericModel;

/**
 * The summary of statistics of the match process results.
 */
public class Summary extends GenericModel {

  @SerializedName("data_assets")
  protected Long dataAssets;
  @SerializedName("entities_count")
  protected Double entitiesCount;
  @SerializedName("singleton_count")
  protected Double singletonCount;
  @SerializedName("distinct_sources")
  protected Long distinctSources;
  @SerializedName("total_records")
  protected Long totalRecords;

  /**
   * Gets the dataAssets.
   *
   * The number of data assets processed by the match process.
   *
   * @return the dataAssets
   */
  public Long getDataAssets() {
    return dataAssets;
  }

  /**
   * Gets the entitiesCount.
   *
   * The total number of entities generated by the match process.
   *
   * @return the entitiesCount
   */
  public Double getEntitiesCount() {
    return entitiesCount;
  }

  /**
   * Gets the singletonCount.
   *
   * The count of entities having size of one.
   *
   * @return the singletonCount
   */
  public Double getSingletonCount() {
    return singletonCount;
  }

  /**
   * Gets the distinctSources.
   *
   * The number of distinct sources of data records.
   *
   * @return the distinctSources
   */
  public Long getDistinctSources() {
    return distinctSources;
  }

  /**
   * Gets the totalRecords.
   *
   * The total number of data records processed by the match process.
   *
   * @return the totalRecords
   */
  public Long getTotalRecords() {
    return totalRecords;
  }
}

